### ISSUE TITLE
Building from source fails (linux)

### ISSUE THREAD

**Issue by yucombinator** [facebook/watchman#1028]
It seems like building from source for a linux machine.

When I am running the `./autogen.sh` step as detailed the install page: https://facebook.github.io/watchman/docs/install.html

I am running in this error:
```
Assessing zlib...
Download with http://www.zlib.net/zlib-1.2.11.tar.gz -> /tmp/fbcode_builder_getdeps-ZmntZdev1749ZwatchmanZbuildZfbcode_builder-root/downloads/zlib-zlib-1.2.11.tar.gz ...
TransientFailure: Failed to download http://www.zlib.net/zlib-1.2.11.tar.gz to /tmp/fbcode_builder_getdeps-ZmntZdev1749ZwatchmanZbuildZfbcode_builder-root/downloads/zlib-zlib-1.2.11.tar.gz: HTTP Error 404: Not Found
```

It seems like zlib download at http://www.zlib.net/zlib-1.2.11.tar.gz has been removed and no longer works, and needs to be updated to a working URL for the build script to work again.

**Comment by chadaustin** [comment]
I believe this is fixed now.

But can you tell me your Linux distribution if you're still having trouble? Also, check out the new installation instructions, where we have RPMs and DEBs for Ubuntu and Fedora: https://facebook.github.io/watchman/docs/install.html

**Comment by DhiaAgrebi** [comment]
Downloaded the watchman source file about an hour ago and the issue still persists.
I'm building it from source using ./autogen.sh on Arch Linux.
Everything is fine except for the HTTP error as https://zlib.net/zlib-1.2.12.tar.gz is no longer available to download.
