### ISSUE TITLE
`watchman version` does not work

### ISSUE THREAD

**Issue by cesarvarela** [facebook/watchman#500]
Something is wrong here, the version command isnt't working:

```
watchman version
Please specify a target and action
```
also

```
watchman -v
ERROR: Unknown option -v
```

and
```
watchman shutdown-server ; watchman 
Please specify a target and action
Please specify a target and action
```

**Comment by wez** [comment]
You've most likely got the npm watchman package installed.  `npm uninstall watchman` should resolve this.  The npm watchman is not at all related to this project.  Our nodejs client bindings are in the `fb-watchman` package on npm.

**Comment by cesarvarela** [comment]
Doh! That was it! Thanks!

**Comment by Miheegz** [comment]
wait so npm install fb-watchman then run watchman watch-del-all? b/c i am still getting the Please specify a target and action

**Comment by wez** [comment]
Facebook's Watchman is a service that is **not** installed through `npm`.  https://facebook.github.io/watchman/docs/install.html has installation instructions.

There is an `npm` module called `watchman` that is completely unrelated and that unfortunately has a name collision and causes confusion.  You will need to uninstall that package if you want to use the Facebook Watchman service.

If you want to use nodejs to talk to the Facebook Watchman service, you can use `npm` to install `fb-watchman`.
