### ISSUE TITLE
The first result for "watchman" on Google is a 404

### ISSUE THREAD

**Issue by Asday** [facebook/watchman#798]
Once one scrolls past the links for the film or visual novel, one finds a link to this project's installation docs (guessing from the URL), but they are [not there](https://facebook.github.io/watchman/docs/install.html).

**Comment by wez** [comment]
@yangshun is there a way to get Docusaurus to redirect the .html suffix to the newer non-.html suffix?  Alternatively, what's the recommended way to get the .html suffix back?

**Comment by yangshun** [comment]
Coincidentally we fixed this issue in https://github.com/facebook/docusaurus/pull/2393. We'll publish a release at the end of this month (tmr).

**Comment by wez** [comment]
@yangshun I finally got around to upgrading and after debugging why the sidebars stopped working as part of the upgrade(!), I can report that this isn't fixed.

`https://facebook.github.io/watchman/docs/install.html`

is the URL and it generates a 404.  If I change that to `https://facebook.github.io/watchman/docs/install/index.html` it gets redirected but I can't change what's in google's cache.

I also tried renaming the source file to `index.html.md` to make this work but something rewrites that internally to `index`.
